# Generated by Django 3.0.6 on 2020-05-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=100000, verbose_name='Lien vers la page')),
                ('link_name', models.CharField(default='Site de recherche', max_length=1025, verbose_name='Nom attribué au lien')),
            ],
        ),
    ]
