# Generated by Django 3.0.6 on 2020-05-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_poster_is_posted_on_tg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='id',
        ),
        migrations.AlterField(
            model_name='poster',
            name='link_name',
            field=models.CharField(default='Site de recherche', max_length=1025, primary_key=True, serialize=False, verbose_name='Nom attribué au lien'),
        ),
    ]
